<html>
    <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href='https://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" type="text/css" href="css/footer_css.css">
    <style>
        p{
            margin-top: 25px;
            text-align: left;
            font-size: 30px;
            margin-left: 15px;
        }
    </style>

    </head>

    <body>

    
  <footer>
    <div class="social-media-links">
      <ul class="folu">
        <li class="foli"><a target="_blank" href="https://www.facebook.com/almoretp/" class="foot fa fa-facebook"></a></li>
        <li class="foli"><a target="_blank" href="https://www.linkedin.com/in/alvaromoret/" class="foot fa fa-linkedin"></a></li>
        <li class="foli"><a target="_blank" href="https://www.instagram.com/alvarom.p/" class="foot fa fa-instagram"></a></li>
        <li class="foli"><a target="_blank" href="https://wa.me/5528999442420" class="foot fa fa-whatsapp"></a></li>
      </ul>
      <p class="footerp">Álvaro Moret - 2018206259</p>
    </div>
  </footer>


</body>
</html>